server:
  port: @server.port@
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: "localhost:29092"
    admin:
      client-id: "fault-detector"
    consumer:
      group-id: "fault-detector"
      max-poll-records: 300
      fetch-min-size: 1024
      fetch-max-wait: 1000
      properties:
        reconnect:
          backoff:
            ms: 15000
    listener:
      concurrency: 1
    ssl:
      trust-store-type: "PKCS12"
      key-store-password: "kenny"
      trust-store-password: "kenny12"
      key-password: "kenny"
      key-store-location: "src/main/resources/cert/keystore.p12"
      key-store-type: "PKCS12"
      trust-store-location: "src/main/resources/cert/truststore.p12"

info:
  version: @project.version@
  stage: dev

operations:
  preAggregationPeriod: 3000
  useServiceConfigPreAggregationPeriod: false
  schedulerPoolSize: 2
  metricsCheckPeriod: 5000
  metricsInitialDelayPeriod: 5000

kafka:
  consumer:
    topic: "fault-detector"
    reconnect-backoff-max-ms: 30000
    retry-backoff-ms: 1000

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
